services:
  app:
    build:
      context: ..                       # путь к корню проекта (где лежит Dockerfile)
      dockerfile: docker/Dockerfile  # путь к Dockerfile относительно context
    container_name: f_app
    ports:
      - "8002:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/fastapi_db
      - LOG_LEVEL=INFO
    networks:
      - app_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  postgres:
    image: postgres:16-alpine
    container_name: fastapi_postgres
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: fastapi_db
    ports:
     - "5433:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network  # ⬅️ Добавить сеть


networks:
  app_network: # ⬅️ Определить сеть
      driver: bridge

volumes:
  postgres_data: